POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhYmlvMzI1IiwiaWQiOiI2NDEwYjQzMDMyNmIxNjg2ZDJhMGI2YWYiLCJpYXQiOjE2Nzg4NzEyNTN9.axVrqmV6PwzgARLMauLHpVgDj-gJ9H-mgIGbiI0-wZM
 
{ 
    "title": "prova363",
    "author": "fabio",
    "url": "http://bo",
    "likes": 1,
    "userId": "6410b430326b1686d2a0b6af"
}

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "fabio325",
    "name": "fabio",
    "password": "1234"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "fabio32",
    "password": "1234"
}

###
DELETE http://localhost:3003/api/blogs/641195999822d0d381995077
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhYmlvMzI1IiwiaWQiOiI2NDEwYjQzMDMyNmIxNjg2ZDJhMGI2YWYiLCJpYXQiOjE2Nzg4NzEyNTN9.axVrqmV6PwzgARLMauLHpVgDj-gJ9H-mgIGbiI0-wZM