POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhYmlvMzIiLCJpZCI6IjY0MTA1MzEwYmI0Y2FlMWExN2E2ZGNiYyIsImlhdCI6MTY3ODc5MjA2N30.U68mYBfcWEb-H2ApoE6Ia-Ke7zJ-24CC-urfmH6d-Ow

{
    "title": "prova8",
    "author": "fabio",
    "url": "http://bo",
    "likes": 1,
    "userId": "64105310bb4cae1a17a6dcbc"
}

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "fabio32",
    "name": "fabio",
    "password": "1234"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "fabio32",
    "password": "1234"
}
