POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "prova11",
    "author": "fabio",
    "url": "http://bo",
    "likes": 1,
    "userId": "640efc33564c290a68ca5a19"
}

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "fabio55",
    "name": "fabio",
    "password": "1234"
}

###
GET http://localhost:3003/api/users