GET http://localhost:3001/api/persons/63f26044554effd70bda1e03


###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/63f26044554effd70bda1e03

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "u",
    "number": "040-123456"
}

###
GET http://localhost:3001/

###
GET https://phonebook-8jxv.onrender.com/api/persons

###
POST https://phonebook-8jxv.onrender.com/api/persons
Content-Type: application/json

{
    "name": "A",
    "number": "040-123456"
}

###
GET https://phonebook-8jxv.onrender.com/info